# Form implementation generated from reading ui file 'ui\res\layout\main.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(445, 361)
        MainWindow.setMaximumSize(QtCore.QSize(445, 445))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/logo"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(480, 619))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 20, 10, 20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_edit_file_path = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_file_path.setObjectName("line_edit_file_path")
        self.horizontalLayout.addWidget(self.line_edit_file_path)
        self.button_open_file = QtWidgets.QPushButton(self.centralwidget)
        self.button_open_file.setObjectName("button_open_file")
        self.horizontalLayout.addWidget(self.button_open_file)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_generate_dm = QtWidgets.QPushButton(self.centralwidget)
        self.button_generate_dm.setObjectName("button_generate_dm")
        self.verticalLayout_3.addWidget(self.button_generate_dm)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        self.label_image.setMinimumSize(QtCore.QSize(250, 250))
        self.label_image.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_image.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.horizontalLayout_2.addWidget(self.label_image)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExcel_megnyit_sa = QtGui.QAction(MainWindow)
        self.actionExcel_megnyit_sa.setObjectName("actionExcel_megnyit_sa")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.line_edit_file_path, self.button_open_file)
        MainWindow.setTabOrder(self.button_open_file, self.button_generate_dm)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DataMatrix Wizard"))
        self.button_open_file.setText(_translate("MainWindow", "Fájl megnyitása"))
        self.button_generate_dm.setText(_translate("MainWindow", "Datamatrix generálás"))
        self.actionExcel_megnyit_sa.setText(_translate("MainWindow", "Excel megnyitása"))
