# Form implementation generated from reading ui file 'ui\res\layout\preferences.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_preferences(object):
    def setupUi(self, preferences):
        preferences.setObjectName("preferences")
        preferences.resize(240, 320)
        self.formLayout = QtWidgets.QFormLayout(preferences)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(preferences)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.line_edit_dxf_name = QtWidgets.QLineEdit(preferences)
        self.line_edit_dxf_name.setObjectName("line_edit_dxf_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_edit_dxf_name)
        self.label_2 = QtWidgets.QLabel(preferences)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.line_edit_dxf_path = QtWidgets.QLineEdit(preferences)
        self.line_edit_dxf_path.setObjectName("line_edit_dxf_path")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_edit_dxf_path)

        self.retranslateUi(preferences)
        QtCore.QMetaObject.connectSlotsByName(preferences)

    def retranslateUi(self, preferences):
        _translate = QtCore.QCoreApplication.translate
        preferences.setWindowTitle(_translate("preferences", "Beállítások"))
        self.label.setToolTip(_translate("preferences", "<html><head/><body><p>A fájl neve, amiként a DataMatrix el lesz mentve</p></body></html>"))
        self.label.setText(_translate("preferences", "DXF név"))
        self.label_2.setText(_translate("preferences", "DXF hely"))
