# Form implementation generated from reading ui file 'ui\res\layout\preferences.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_preferences(object):
    def setupUi(self, preferences):
        preferences.setObjectName("preferences")
        preferences.resize(450, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(preferences.sizePolicy().hasHeightForWidth())
        preferences.setSizePolicy(sizePolicy)
        preferences.setMinimumSize(QtCore.QSize(0, 100))
        preferences.setMaximumSize(QtCore.QSize(450, 100))
        self.gridLayout = QtWidgets.QGridLayout(preferences)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(preferences)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.line_edit_dxf_path = QtWidgets.QLineEdit(preferences)
        self.line_edit_dxf_path.setObjectName("line_edit_dxf_path")
        self.gridLayout.addWidget(self.line_edit_dxf_path, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(preferences)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(preferences)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.button_browse_path = QtWidgets.QPushButton(preferences)
        self.button_browse_path.setMaximumSize(QtCore.QSize(30, 16777215))
        self.button_browse_path.setObjectName("button_browse_path")
        self.gridLayout.addWidget(self.button_browse_path, 1, 2, 1, 1)
        self.line_edit_dxf_name = QtWidgets.QLineEdit(preferences)
        self.line_edit_dxf_name.setObjectName("line_edit_dxf_name")
        self.gridLayout.addWidget(self.line_edit_dxf_name, 0, 1, 1, 1)
        self.line_edit_dxf_size = QtWidgets.QLineEdit(preferences)
        self.line_edit_dxf_size.setFrame(True)
        self.line_edit_dxf_size.setClearButtonEnabled(False)
        self.line_edit_dxf_size.setObjectName("line_edit_dxf_size")
        self.gridLayout.addWidget(self.line_edit_dxf_size, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(preferences)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)

        self.retranslateUi(preferences)
        QtCore.QMetaObject.connectSlotsByName(preferences)

    def retranslateUi(self, preferences):
        _translate = QtCore.QCoreApplication.translate
        preferences.setWindowTitle(_translate("preferences", "Beállítások"))
        self.label_2.setText(_translate("preferences", "DXF hely"))
        self.label.setToolTip(_translate("preferences", "<html><head/><body><p>A fájl neve, amiként a DataMatrix el lesz mentve</p></body></html>"))
        self.label.setText(_translate("preferences", "DXF név"))
        self.label_3.setText(_translate("preferences", "DXF méret"))
        self.button_browse_path.setText(_translate("preferences", "..."))
        self.label_4.setText(_translate("preferences", "mm"))
